<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DarkColony.Engine\DarkColony.Engine.csproj" />
    <ProjectReference Include="..\..\src\DarkColony.Presentation\DarkColony.Presentation.csproj" />
  </ItemGroup>
</Project>
